- build.cmd
- test/Microsoft.Framework.Cache.Redis.Tests/Infrastructure/RedisTestConfig.cs
- Change default packages path
- Change KRE to DOTNET
@davidfowl
> React to runtime renaming

- test/Microsoft.AspNet.Session.Tests/SessionTests.cs
> Reacting to ILoggerStructure changes

- src/Microsoft.Framework.Cache.Memory/CachePreservationPriority.cs
- src/Microsoft.Framework.Cache.Memory/EntryLinkHelpers.cs
- src/Microsoft.Framework.Cache.Memory/EvictionReason.cs
- src/Microsoft.Framework.Cache.Memory/ICacheSetContext.cs
- src/Microsoft.Framework.Cache.Memory/IEntryLink.cs
- src/Microsoft.Framework.Cache.Memory/IExpirationTrigger.cs
- src/Microsoft.Framework.Cache.Memory/IMemoryCache.cs
- src/Microsoft.Framework.Cache.Memory/project.json
@anpete would like to use this in EF
> Target net45

- NuGet.Config
- samples/MemoryCacheConcurencySample/project.json
- samples/MemoryCacheSample/project.json
- samples/ProfilingSample/project.json
- samples/RedisCacheSample/project.json
- samples/SessionSample/project.json
- src/Microsoft.AspNet.Session/project.json
- src/Microsoft.Framework.Cache.Distributed/project.json
- src/Microsoft.Framework.Cache.Memory/project.json
- src/Microsoft.Framework.Cache.Redis/project.json
- test/Microsoft.AspNet.Session.Tests/project.json
- test/Microsoft.Framework.Cache.Distributed.Tests/project.json
- test/Microsoft.Framework.Cache.Memory.Tests/project.json
- test/Microsoft.Framework.Cache.Redis.Tests/project.json
@Tratcher 
Just FYI...the Xunit packages are not available on public Nuget feed and we are figuring out if we need to create a separate feed for external packages, but other than that please take a look at the changes to other packages.
> Changed package versions to beta2

- build.cmd
- build.sh
- samples/MemoryCacheConcurencySample/project.json
- samples/MemoryCacheSample/project.json
- samples/ProfilingSample/project.json
- samples/RedisCacheSample/project.json
- src/Microsoft.Framework.Cache.Distributed/project.json
- src/Microsoft.Framework.Cache.Interfaces/project.json
- src/Microsoft.Framework.Cache.Memory/EntryLinkHelpers.cs
- src/Microsoft.Framework.Cache.Memory/project.json
- src/Microsoft.Framework.Cache.Redis/project.json
- test/Microsoft.Framework.Cache.Distributed.Tests/project.json
- test/Microsoft.Framework.Cache.Memory.Tests/project.json
- test/Microsoft.Framework.Cache.Redis.Tests/project.json
Prepping to be merged once ready.
> Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

- src/Microsoft.Framework.Caching.Distributed/CachingServicesExtensions.cs
Fixes : https://github.com/aspnet/Caching/issues/43
@HaoK
> Rename AddCachingServices -> AddCaching

- src/Microsoft.Framework.Caching.Interfaces/project.json
- src/Microsoft.Framework.Caching.Memory/CacheEntry.cs
- src/Microsoft.Framework.Caching.Memory/EntryLinkHelpers.cs
- src/Microsoft.Framework.Caching.Memory/MemoryCache.cs
- src/Microsoft.Framework.Caching.Memory/project.json
This is part of aspnet/EntityFramework#1952
> Target netcore451

- src/Microsoft.Framework.Caching.Abstractions/project.json
- src/Microsoft.Framework.Caching.Memory/CacheEntry.cs
- src/Microsoft.Framework.Caching.Memory/EntryLinkHelpers.cs
- src/Microsoft.Framework.Caching.Memory/MemoryCache.cs
- src/Microsoft.Framework.Caching.Memory/project.json
> dotnet all the things

- src/Microsoft.Framework.Caching.Memory/CacheEntry.cs
- src/Microsoft.Framework.Caching.Memory/MemoryCache.cs
- Avoid unnecessary delegate allocations (static cached delegates via C# compiler)
- Avoid unnecessary enumerator allocations when enumerating `List<T>` and `Dictionary<TKey, TValue>`
- Specify `TaskCreationOptions.DenyChildAttach` when calling `Task.Factory.StartNew` to prevent child tasks attaching to the parent task ([details](http://blogs.msdn.com/b/pfxteam/archive/2012/09/22/new-taskcreationoptions-and-taskcontinuationoptions-in-net-4-5.aspx))
- Thread safe delegate invocation (via null-propagation operator)
> Avoid unnecessary allocations

- src/Microsoft.Framework.Caching.SqlConfig/project.json
- src/Microsoft.Framework.Caching.SqlServer/project.json
@victorhurdugaci I missed adding this information in these new projects...I will verify other repos too and send out PRs if necessary
> Added missing repository information

- src/Microsoft.Framework.Caching.SqlServer/DatabaseOperations.cs
- src/Microsoft.Framework.Caching.SqlServer/MonoDatabaseOperations.cs
> [Fixes #80] Fix exception rethrow to preserve call stack

- test/Microsoft.Framework.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs
> Adds regression test for key equality comparison behavior.

- src/Microsoft.Framework.Caching.Abstractions/project.json
- src/Microsoft.Framework.Caching.Redis/project.json
> Added net45 TFM to Redis project

- src/Microsoft.Framework.Caching.SqlServer/SqlServerCacheExtensions.cs
- test/Microsoft.Framework.Caching.SqlServer.Tests/TestOptions.cs
> Remove ConfigureSqlServerCache method

- test/Microsoft.Extensions.Caching.Memory.Tests/project.json
> Enable Microsoft.Extensions.Caching.Memory.Tests on CoreCLR.

- test/Microsoft.Extensions.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs
> Fix slow test

- samples/SqlServerCacheConcurencySample/Program.cs
- samples/SqlServerCacheSample/Program.cs
- src/Microsoft.Extensions.Caching.SqlServer/SqlServerCacheOptions.cs
> SqlServerCacheOptions implements IOptions<>

- src/Microsoft.Extensions.Caching.Memory/CacheEntry.cs
> Thread safe way of not invoking Eviction callbacks more than once

- .gitattributes
- .gitignore
- .travis.yml
- appveyor.yml
- build.cmd
- build.sh
- test/Microsoft.Extensions.Caching.Memory.Tests/project.json
- test/Microsoft.Extensions.Caching.Redis.Tests/project.json
- test/Microsoft.Extensions.Caching.SqlServer.Tests/project.json
> Build with dotnet

- src/Microsoft.Extensions.Caching.SqlConfig/Program.cs
- src/Microsoft.Extensions.Caching.SqlConfig/project.json
> Unsourced CommandLineUtils

- test/Microsoft.Extensions.Caching.Memory.Tests/GcNotificationTests.cs
> Disable test that fails on Mono.

- samples/MemoryCacheConcurencySample/project.json
- samples/MemoryCacheSample/project.json
- samples/ProfilingSample/project.json
- samples/SqlServerCacheConcurencySample/project.json
- samples/SqlServerCacheSample/project.json
- src/Microsoft.Extensions.Caching.Abstractions/project.json
- src/Microsoft.Extensions.Caching.Memory/EntryLinkHelpers.cs
- src/Microsoft.Extensions.Caching.Memory/project.json
- test/Microsoft.Extensions.Caching.Memory.Tests/project.json
- test/Microsoft.Extensions.Caching.SqlServer.Tests/project.json
> Remove netcore50

- NuGetPackageVerifier.json
- src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheEntryExtensions.cs
- src/Microsoft.Extensions.Caching.Abstractions/project.json
- src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs
- src/Microsoft.Extensions.Caching.Memory/project.json
- src/Microsoft.Extensions.Caching.Redis/project.json
- src/Microsoft.Extensions.Caching.SqlServer/project.json
- src/dotnet-sql-cache/project.json
> Enabled xml doc generation

- src/dotnet-sql-cache/project.json
> Update Sql Cache tool to actually run

- samples/SqlServerCacheConcurencySample/project.json
- samples/SqlServerCacheSample/project.json
- src/Microsoft.Extensions.Caching.SqlServer/SqlParameterCollectionExtensions.cs
- src/dotnet-sql-cache/SqlQueries.cs
- test/Microsoft.Extensions.Caching.SqlServer.Tests/SqlServerCacheWithDatabaseTest.cs
- test/Microsoft.Extensions.Caching.SqlServer.Tests/project.json
> [Fixes #146] Maximum Key Length on Primary Key

- src/Microsoft.Extensions.Caching.Abstractions/project.json
- src/Microsoft.Extensions.Caching.Memory/CacheEntry.cs
- src/Microsoft.Extensions.Caching.Memory/CacheEntryHelper.cs
- src/Microsoft.Extensions.Caching.Memory/project.json
Part of https://github.com/aspnet/EntityFramework/pull/5021
> Cross-compile to netcore50 to support EF on UWP

- src/dotnet-sql-cache/project.json
> Make dotnet-sql-cache a portable app

- samples/MemoryCacheConcurencySample/project.json
- samples/MemoryCacheSample/project.json
- samples/ProfilingSample/project.json
- samples/RedisCacheSample/project.json
- samples/SqlServerCacheConcurencySample/project.json
- samples/SqlServerCacheSample/project.json
- src/dotnet-sql-cache/project.json
- test/Microsoft.Extensions.Caching.Memory.Tests/project.json
- test/Microsoft.Extensions.Caching.SqlServer.Tests/project.json
> Migrate tests/samples/tools to portable

- src/Microsoft.Extensions.Caching.SqlConfig.Tools/Program.cs
@moozzyk 
Sample error messages:
- An error occurred. Invalid Sql server connection string 'a'. Format of the initialization string does not conform to specification starting at index 0.
- An error occurred while trying to create the table and index. The specified schema name "foo" either does not exist or you do not have permission to use it.
> Fix error messages in dotnet-sql-cache tool

- makefile.shade
- src/Microsoft.Extensions.Caching.Abstractions/project.json
- src/Microsoft.Extensions.Caching.Memory/project.json
- src/Microsoft.Extensions.Caching.Redis/project.json
- src/Microsoft.Extensions.Caching.SqlConfig.Tools/project.json
- src/Microsoft.Extensions.Caching.SqlServer/project.json
> Modify version to preview1

- src/Microsoft.Extensions.Caching.Memory/CacheEntry.cs
- src/Microsoft.Extensions.Caching.Memory/CacheEntryHelper.cs
- src/Microsoft.Extensions.Caching.Memory/CacheEntryStack.cs
- src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/CacheEntryScopeExpirationTests.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs
> Fixing race condition

- src/Microsoft.Extensions.Caching.Memory/MemoryCacheServiceCollectionExtensions.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/CacheServiceExtensionsTests.cs
> Fixing potential cache key collisions between IDistributedCache and IMemoryCache

- src/Microsoft.Extensions.Caching.Redis/RedisCache.cs
- test/Microsoft.Extensions.Caching.Redis.Tests/TimeExpirationTests.cs
> Fix RelativeExpiration with SlidingExpiration

- src/Microsoft.Extensions.Caching.Abstractions/DistributedCacheExtensions.cs
- src/Microsoft.Extensions.Caching.Memory/MemoryDistributedCache.cs
- src/Microsoft.Extensions.Caching.Redis/RedisCache.cs
- test/Microsoft.Extensions.Caching.Redis.Tests/RedisCacheSetAndRemoveTests.cs
#169 
@JunTaoLuo @Tratcher @Eilon @muratg
> Adding Get/Set String to IDistributedCache

- src/Microsoft.Extensions.Caching.Abstractions/project.json
- src/Microsoft.Extensions.Caching.Memory/project.json
- src/Microsoft.Extensions.Caching.Redis/project.json
- src/Microsoft.Extensions.Caching.SqlServer/project.json
> Update to RTM version

- src/Microsoft.Extensions.Caching.Memory/CacheEntryHelper.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs
> Fix exception when changing AppDomains

- src/Microsoft.Extensions.Caching.Memory/CacheEntry.cs
- src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs
> French to English

- src/Microsoft.Extensions.Caching.Memory/MemoryDistributedCache.cs
- src/Microsoft.Extensions.Caching.Redis/RedisCache.cs
- src/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.cs
- src/Microsoft.Extensions.Caching.SqlServer/SqlServerCacheOptions.cs
- test/Microsoft.Extensions.Caching.Redis.Tests/Infrastructure/RedisTestConfig.cs
- test/Microsoft.Extensions.Caching.SqlServer.Tests/SqlServerCacheWithDatabaseTest.cs
> [Design] [Fixes #209] SQLCache Set should allow a null timeout

- samples/MemoryCacheSample/MemoryCacheWeakReferenceExtensions.cs
- samples/MemoryCacheSample/Program.cs
- samples/MemoryCacheSample/WeakToken.cs
> Sample for caching with weak references

- samples/RedisCacheSample/project.json
- src/Microsoft.Extensions.Caching.Redis/project.json
- test/Microsoft.Extensions.Caching.Redis.Tests/project.json
> Updated Redis cache project to support .NET Core

- src/Microsoft.Extensions.Caching.SqlConfig.Tools/Microsoft.Extensions.Caching.SqlConfig.Tools.xproj
- src/Microsoft.Extensions.Caching.SqlConfig.Tools/project.json
Resolves #227
NB: merges into 1.0.0-preview3 branch
cc @pranavkm @muratg
> Downgrade CLI tool dependencies to 1.0.0 runtime release

- src/Microsoft.Extensions.Caching.Redis/project.json
[Fixes #121] Redis is not supported for .netCore, any plans?
@muratg @Tratcher
> Updated StackExchange.Redis package to RTM

- makefile.shade
- src/Microsoft.Extensions.Caching.Abstractions/project.json
- src/Microsoft.Extensions.Caching.Memory/project.json
- src/Microsoft.Extensions.Caching.Redis/project.json
- src/Microsoft.Extensions.Caching.SqlServer/project.json
> Remove build quality pinning

- src/Microsoft.Extensions.Caching.Abstractions/project.json
- src/Microsoft.Extensions.Caching.Memory/project.json
- src/Microsoft.Extensions.Caching.Redis/project.json
- src/Microsoft.Extensions.Caching.SqlConfig.Tools/project.json
- src/Microsoft.Extensions.Caching.SqlServer/project.json
- test/Microsoft.Extensions.Caching.Memory.Tests/project.json
- test/Microsoft.Extensions.Caching.Redis.Tests/project.json
- test/Microsoft.Extensions.Caching.SqlServer.Tests/project.json
> rel/1.0.1: Update versions to 1.0.1/1.0.0-preview4

- src/Microsoft.Extensions.Caching.Memory/CacheEntry.cs
- src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/CacheEntryScopeExpirationTests.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/CompactTests.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs
- test/Microsoft.Extensions.Caching.Redis.Tests/Microsoft.Extensions.Caching.Redis.Tests.xproj
#242
Performance results:
Scenario | Before | After
--- | --- | ---
benchmarks: memorycacheplaintext | 280249.98 | 886543.73
benchmarks: memorycacheplaintextsetremove | 123328.57 | 689634.29
> Concurrent dictionary implementation for MemoryCache

- src/Microsoft.Extensions.Caching.Redis/RedisCache.cs
> Lock on creating redis connections

- src/Microsoft.Extensions.Caching.Memory/CacheEntry.cs
> Concurrent updates to parent requires synchronization

- src/Microsoft.Extensions.Caching.Memory/CacheEntryHelper.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs
@pranavkm 
There are similar cases of this in a few repos, I saw you didn't remove the test in Mvc when doing the net46 change. Haven't checked other repos yet.
> Remove old test

- samples/SqlServerCacheConcurencySample/Program.cs
- samples/SqlServerCacheConcurencySample/SqlServerCacheConcurencySample.csproj
- samples/SqlServerCacheSample/SqlServerCacheSample.csproj
This PR removes all references to PlatformAbstractions.
Part of aspnet/PlatformAbstractions#50
> react to removal of PlatformAbstractions

- src/Microsoft.Extensions.Caching.Abstractions/IDistributedCache.cs
- src/Microsoft.Extensions.Caching.Abstractions/breakingchanges.netcore.json
- src/Microsoft.Extensions.Caching.Memory/MemoryDistributedCache.cs
- src/Microsoft.Extensions.Caching.Memory/breakingchanges.netcore.json
- src/Microsoft.Extensions.Caching.Memory/breakingchanges.netframework.json
- src/Microsoft.Extensions.Caching.Redis/RedisCache.cs
- src/Microsoft.Extensions.Caching.Redis/breakingchanges.netcore.json
- src/Microsoft.Extensions.Caching.Redis/breakingchanges.netframework.json
- src/Microsoft.Extensions.Caching.SqlServer/DatabaseOperations.cs
- src/Microsoft.Extensions.Caching.SqlServer/IDatabaseOperations.cs
- src/Microsoft.Extensions.Caching.SqlServer/MonoDatabaseOperations.cs
- src/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/CacheServiceExtensionsTests.cs
> Add cancellation token support

- .gitignore
- src/Microsoft.Extensions.Caching.Abstractions/DistributedCacheExtensions.cs
- src/Microsoft.Extensions.Caching.Abstractions/breakingchanges.netcore.json
Missed this in https://github.com/aspnet/Caching/pull/306
> Use CancellationToken in DistributedCacheExtensions

- build/common.props
- build/dependencies.props
- samples/MemoryCacheConcurencySample/MemoryCacheConcurencySample.csproj
- samples/MemoryCacheFileWatchSample/MemoryCacheFileWatchSample.csproj
- samples/MemoryCacheSample/MemoryCacheSample.csproj
- samples/ProfilingSample/ProfilingSample.csproj
- samples/RedisCacheSample/RedisCacheSample.csproj
- samples/SqlServerCacheConcurencySample/SqlServerCacheConcurencySample.csproj
- samples/SqlServerCacheSample/SqlServerCacheSample.csproj
- src/Microsoft.Extensions.Caching.Abstractions/Microsoft.Extensions.Caching.Abstractions.csproj
- src/Microsoft.Extensions.Caching.Memory/Microsoft.Extensions.Caching.Memory.csproj
- src/Microsoft.Extensions.Caching.Redis/Microsoft.Extensions.Caching.Redis.csproj
- src/Microsoft.Extensions.Caching.SqlServer/Microsoft.Extensions.Caching.SqlServer.csproj
- test/Microsoft.Extensions.Caching.Memory.Tests/Microsoft.Extensions.Caching.Memory.Tests.csproj
- test/Microsoft.Extensions.Caching.Redis.Tests/Microsoft.Extensions.Caching.Redis.Tests.csproj
- test/Microsoft.Extensions.Caching.SqlServer.Tests/Microsoft.Extensions.Caching.SqlServer.Tests.csproj
> Target .NET Standard 2.0

- src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs
- src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs
Summary of the changes (Less than 80 chars)
- Added suitable null checks to the extension method arguments
Addresses #316
> Added suitable null checks to the extension method arguments

- src/Microsoft.Extensions.Caching.Redis/RedisCache.cs
- src/Microsoft.Extensions.Caching.SqlServer/DatabaseOperations.cs
- src/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.cs
-  Pass on CancellationToken in RedisCache.cs, DataBaseOperations.cs and SqlServerCache
Addresses #365
> Pass on CancellationToken

- src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs
- test/Microsoft.Extensions.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs
> MemoryCache generic TryGetValue return false when incompatible type used
